### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by sjnm8** [daniil934/test1#1]
Напишите программу, которая выводит на экран числа от 1 до 100. При этом вместо чисел, кратных трем, программа должна выводить слово «Fizz», а вместо чисел, кратных пяти — слово «Buzz». Если число кратно и 3, и 5, то программа должна выводить слово «FizzBuzz»

**Comment by daniil934** [comment]
[Fizzbuzz_prog.txt](https://github.com/daniil934/test1/files/9076541/Fizzbuzz_prog.txt)

**Comment by sjnm8** [comment]
Убрать лишние перменные
Порефакторить проверки
разобраться с гемами (gem)
Пофиксить табуляцию (смотри rubocop) (смотри подключение модулей require) (почитай про модули)
Сделать класс с методом для расчета ( смотри классы, конструктор, методы)
Добавить выбор диапазона, сейчас у тебя 1..100, дать возможность добавить динамически любые варинты (пример от 200..1000, или 1000..5000)
Подсказка, для этого нужен инишалайзер класса(метод) и инстанс переменные
Написать тесты (rspec.info)
Сделать пул реквест

**Comment by sjnm8** [comment]
```rb
def test(arg)
  puts arg
end
```

**Comment by sjnm8** [comment]
@daniil934 

1. В руби, обычно не используют `for`, потому что есть другие способы писать тоже самое проще.
Посмотри метод `each`

```rb
(@start_num...@last_num).each do |i|
  if i % 3 == 0 ...
end
```

2. Старайся называть методы так, чтобы было понятно, что они делают. Пример `print_nums`

3. Обычно, с инстанс переменными не работают напрямую. Для них используют геттеры и сеттеры.
Посмотри `attr_reader`, `attr_writter`, `attr_accessor`
```rb
class FizzBuzz
  attr_accessor :start_num
  attr_accessor :last_num

  def initialize(start_num, last_num)
    @start_num = start_num
    @last_num = last_num
  end

  def print_nums
    (start_num...last_num).each do |i|
      ...
    end
  end
end
```
